### ISSUE TITLE
Error adding storage [User already has a storage with such chat id]

### ISSUE THREAD

**Issue by LifeViwer** [Dominux/Pentaract#26]
There was an error when adding a storage, but I added it to the list and it doesn’t allow me to add it again.

User already has a storage with such chat id

![image](https://github.com/Dominux/Pentaract/assets/36803375/5d835dcf-c0fa-411c-80b5-c42d042ee53c)

![image](https://github.com/Dominux/Pentaract/assets/36803375/809bf48c-002e-4426-91ab-cfd9212bd1ad)

**Comment by Dominux** [comment]
Hi, sorry for long response, it's not so big project yet, I am the only contributor here and got a full-time job besides

As for the problem, it seems to be an unexpected behavior

After some research I got that there's only one place where this error is raised. I assume that you might have already created the same storage, but it's not displayed for some reason.

So, to help me understand your problem pls run next commands in terminal (if you changed db creds and name - set yours in the command) and send the result:

```sh
docker exec -it pentaract_db psql -U pentaract --dbname pentaract -c "select * from storages s full join access a on s.id = a.project_id"
```
