### ISSUE TITLE
Add user-bot support to file size increases and speed up

### ISSUE THREAD

**Issue by smyhlin** [Dominux/Pentaract#27]
I did some kind of it on my project and  uploading/downloading greatly rise. And i could upload such way up to 366 bleach series quickly (each 400+mb).

So about file sizes... You can use user-bot instances which allows yo to upload files up to 2000mb or 4000mb (tg premium with speed boost). So... also it can be useful to use chunk system for more file size etc. Because 20mb chunk for some PC resources consumable

**Comment by smyhlin** [comment]
Some screenshots. And one else: if you have **more than one** tg account it can be useful too. You can create **more** bots)![Screenshot_2024-01-08-07-28-19-29_0b342c26d6c44f3c8d2de40eabb4e1da.jpg](https://github.com/Dominux/Pentaract/assets/37741855/d3b42cc3-af17-403b-8db1-b2fdda752e33)

![Screenshot_2024-01-08-07-28-46-95_0b342c26d6c44f3c8d2de40eabb4e1da.jpg](https://github.com/Dominux/Pentaract/assets/37741855/fb9ec40e-7dd3-410c-8aef-6cd5097c6173)

![Screenshot_2024-01-08-07-30-03-34_0b342c26d6c44f3c8d2de40eabb4e1da.jpg](https://github.com/Dominux/Pentaract/assets/37741855/ee4be4ac-ef8c-4883-84f1-89f1c1373736)

![Screenshot_2024-01-08-07-29-19-67_0b342c26d6c44f3c8d2de40eabb4e1da.jpg](https://github.com/Dominux/Pentaract/assets/37741855/330e6eb9-9c47-4cad-82e4-6ff71e886766)

**Comment by Dominux** [comment]
Hey, man

TBH, I don't have a time for this feature for now.

Nevertheless, you could do it on your own - by contributing to the project. I think this feature will definitely enhance it!

**Comment by Dominux** [comment]
Btw, what do u meen?

> 20mb chunk for some PC resources consumable

Like 20mb chunks are gonna take more resources than 2000mb ones?

**Comment by smyhlin** [comment]
> Like 20mb chunks are gonna take more resources than 2000mb ones?

I mean than no need to chunk files less than user-bot max file size limit, it can save some time and pc resources.
