### ISSUE TITLE
Problem with storage

### ISSUE THREAD

**Issue by HectorArrives** [Dominux/Pentaract#28]
Hi, I had a bug with your program, namely I created a storage and connected the bot (uploaded the file) and the storage just disappeared after a reboot, and it doesn't help. Can you help me decide?

Same issue as this post - https://github.com/Dominux/Pentaract/issues/26

Thank you!

**Comment by FlashPo1ntt** [comment]
> Привет, у меня была ошибка в вашей программе, а именно я создал репозиторий и подключил боту (загрузил файл), и после перезагрузки репозиторий просто пропал, и это не помогает. Можете ли вы помочь мне решить?
> 
> Та же проблема, что и в седьмом посте — [№26.](https://github.com/Dominux/Pentaract/issues/26)
> 
> Спасибо!

Здравствуйте я не понимаю о чем вы? У меня нет репозиториев

**Comment by HectorArrives** [comment]
Я извиняюсь не правильный перевод. Я имел виду хранилище

**Comment by FlashPo1ntt** [comment]
> Я извиняюсь не правильный перевод. Я имел виду хранилище

Нет бро я имею ввиду я не разбираюсь в GitHub я тут только зарегистрировался и ничего не делал,и тут ты мне пишешь.Прости я просто не понимаю о чем ты хочешь сказать

**Comment by FlashPo1ntt** [comment]
> Давай так, ты работаешь над этим проетом?

Нет

**Comment by HectorArrives** [comment]
> > Давай так, ты работаешь над этим проетом?
> 
> Нет

Тогда ты не поймёшь что мне нужно
