### ISSUE TITLE
Request for Modification to Program Default Settings to Support serv00 Host

### ISSUE THREAD

**Issue by Raimbaulty** [Dominux/Pentaract#31]
Dear author,

I am reaching out to request a modification to the default settings of the program. Currently, when the program is launched, it does not check whether the database has been established, which poses a challenge for users hosting the program on serv00. As serv00's built-in PostgreSQL cannot be used and access to PostgreSQL with superuser privileges is required, it is essential to incorporate this requirement into the program's default settings.

I kindly request that you consider implementing a feature in the program that checks for the existence of the database upon startup. This enhancement would greatly benefit users hosting the program on serv00 and ensure a smoother experience.

Thank you for your attention to this matter.

Best regards,

Raimbault

**Comment by Dominux** [comment]
sup m8 ya can make it on ur own right?

**Comment by Raimbaulty** [comment]
Hi Dominux,

Thanks for your response. I understand that I might be able to implement this feature on my own. However, I've found a free public database, Supabase, that could potentially solve my issue.

Despite this, I would still prefer to store my data on my own host for two reasons. Firstly, the speed of public databases can be slow, and secondly, I believe it would be more efficient to have the program check for the existence of the database upon startup.

I believe this improvement could greatly benefit not only me but also other users who host the program on serv00 and face similar challenges.

I'll try to figure this out on my own, but I might come back for your support if I encounter any difficulties. I hope you understand and can provide further assistance if needed.

Best regards,

Raimbault

**Comment by Dominux** [comment]
but supabase is saas not a db bro

i mean it can be used as a db but it's not intented for such purposes. i haven't watched their progress for the last year so I may not know they enhanced their service to a google drive like service but i genuinely doubt they did, it's a saas after all so using it as a cloud drive is like buying ipad and using it as mp3 player

Anyway, the main difference here is **supabase does not provide a fully free access and unlimited drive capacity like Pentaract does**

But if it's not what you were looking for - than you are right, afterall you are the only who knows what they need
