### ISSUE TITLE
"Something went wrong" when uploading files

### ISSUE THREAD

**Issue by hhtnFxQVwQntBLkULKjy** [Dominux/Pentaract#34]
How to solve the problem like the title?
First create a channel, write the channel ID into the chat id, create a robot, and copy the robot's token, which is the time API, Copy it to Storage workers. How to solve this problem? Please help me.

**Comment by skalerr** [comment]
Same problem

**Comment by 36-H** [comment]
I'm having the same problem.

**Comment by Dominux** [comment]
Maybe some logs or meta info? Cuz bug can't be reproduced in 100% of cases
